# Generated by Django 5.2.3 on 2025-07-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_withdrawal_amount_alter_withdrawal_card_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='withdraw_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
