# Generated by Django 5.2.3 on 2025-07-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_order_deliver_order_delivered_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliver_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
