# Generated by Django 5.2.3 on 2025-07-03 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_order_deliver_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='deliver_date',
        ),
    ]
