# Generated by Django 5.2.3 on 2025-07-03 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_remove_order_deliver_date'),
        ('authenticate', '0002_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='authenticate.district'),
        ),
    ]
