# Generated by Django 5.2.3 on 2025-07-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_order_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivered_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
